import { defineConfig } from "wxt";

export default defineConfig({
	// Relative to project root
	srcDir: "src", // default: "."

	manifest: {
		name: "Netflix Controller",
		version: "1.0.7",
		description:
			"Control Netflix in your browser with a gamepad or controller.",
		permissions: ["storage", "tabs", "scripting"],
		host_permissions: ["*://*.netflix.com/*"],
		browser_specific_settings: {
			gecko: {
				// Set a stable ID so Firefox enables storage in dev builds
				id: "netflix-controller@jumplink.eu",
			},
		},
		icons: {
			16: "/assets/icon16.png",
			32: "/assets/icon32.png",
			48: "/assets/icon48.png",
			128: "/assets/icon128.png",
			512: "/assets/icon512.png",
		},
		web_accessible_resources: [
			{
				resources: [
					"assets/buttons/*/*.png",
					"assets/styles/content.css",
					"netflix-main-world.js",
				],
				matches: ["*://*.netflix.com/*"],
			},
		],
	},

	hooks: {
		"build:manifestGenerated": (_wxt, manifest) => {
			// Add exclude_matches to the content script generated by defineContentScript
			if (manifest.content_scripts?.[0]) {
				manifest.content_scripts[0].exclude_matches = [
					"*://help.netflix.com/*",
				];
				manifest.content_scripts[0].all_frames = true;
			}
		},
	},
});
